### ISSUE TITLE
2983	 Security of the Online Booking System

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#1]
Implement the security of our Online booking system. The points to be taken care of are as follows: 

1. Secured network traffic Convert your website to HTTPS, get a certificate for your website.
2. Encrypted/ Decrypt the personal information (PI) 
3. Encrypt the existing PI data in your database.
4. Real time inventory check before booking to avoid any and all scenarios of double bookings.

**Comment by amit-ros** [comment]
Encryption/ Decryption module is added to the code base and implemented at all the places required.
Needs to be tested throughly. Will be rolled out once the booking flow change is validated completely.
