### ISSUE TITLE
3079 Purchase SSL for booking system

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#10]
The details of digital certificate is available on http://mitsu.in/digital-certificate. Can you advise if we should buy it from Mitsu or should we buy it directly from verisign. 

Also advise which SSL should we go for Positive SSL, Comodo SSL or Positive SSL Wildcard.

**Comment by farhorizonindia** [comment]
Amit, let me know if we need to procure this.

**Comment by amit-ros** [comment]
Reviewed this. I believe Positive SSL Wildcard is the best value for money, although Comodo is not bad but according to the reviews it's support is not too great.

So if I have to choose I will probably go with Positive SSL Wildcard, but if money is a factor then Comodo could be the choice.

**Comment by farhorizonindia** [comment]
Should I take Comodo now and then we can take the Positive one later. Will you have to change your coding later if we change the certificate. Please advise.

**Comment by amit-ros** [comment]
Yeah. I think that will work. You can take Comodo for now and later on upgrade it to Positive.

As far as code changes are concerned, not necessarily we have to change anything in code but there could be something which may force us to change. I would say you can apply the certificate to the test domain and once validated there  we can apply it to the production domain.

**Comment by farhorizonindia** [comment]
Amit can you review these SSL again https://in.godaddy.com/web-security/ssl-certificate?isc=sshl5in34. They seem to be different. The comodo is not available on Godaddy.
