### ISSUE TITLE
3135 Add Google Analytics code on Cruise Booking System

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#11]
Request you to add the Google tracking code on the page http://adventureresortscruises.in and the last invoice page which comes after the payment is done

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-81338023-3', 'auto');
  ga('send', 'pageview');

</script>

**Comment by farhorizonindia** [comment]
Amit, can you do this, as I want to track who all are coming to my reservation system.

**Comment by amit-ros** [comment]
Added the code in PaymentGatewayRespose.aspx and SearchProperty.aspx pages.

Kindly Test.
