### ISSUE TITLE
3137 Bug: Hotel Booking: Book button is not working

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#12]
The book button on Hotel Booking page is not working. We are getting this issue with Dera Village Retreat, Kalakho on selecting any random checkin and checkout.

I have attached the screenshot of the same along with URL.
![hotel booking](https://cloud.githubusercontent.com/assets/24309056/21340995/0ff9dde6-c6b0-11e6-9387-53456af67213.GIF)

**Comment by amit-ros** [comment]
This issue is happening because MaxRooms value is 0 in table tblAgentMaxRooms for the agent id 248 and accommodation id 6 (Kalakho).


Need to discuss what is expected here.

**Comment by farhorizonindia** [comment]
Its working after the max bookable room was made to 5 in the database
