### ISSUE TITLE
3143 AfterBookingActions is showing cancelled booking

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#13]
AfterBookingactions.aspx cancelled booking showing in the section: 

Other Bookings Within The Same Date Are: 

![cancelled booking](https://cloud.githubusercontent.com/assets/24309056/21415283/3397d0ee-c82e-11e6-9022-e7b253de47c7.GIF)

**Comment by amit-ros** [comment]
Database change is made to fix this issue in stored proc "up_GetBookingsWithinDates".

Kindly re-test.

**Comment by farhorizonindia** [comment]
This is working.
