### ISSUE TITLE
3159 Bug: Reservations: Connection timeout

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#14]
After login the session is automatically logging out after 2-3 minutes and ask login again.

**Comment by amit-ros** [comment]
Please let me know if this is still happening.

**Comment by farhorizonindia** [comment]
Still happening when we press forward or backward on booking chart as shown on screenshare.

**Comment by amit-ros** [comment]
Added few try catch blocks in code to catch the issue which is causing this automatic logout on the navigation of the BookingChart view.

**Comment by amit-ros** [comment]
Multiple users are using the same user id.
Rohit will allocate separate ids to them and then we will evaluate if the issue happens again.

**Comment by farhorizonindia** [comment]
Amit the problem with the session logout is completely resolved in the bluehost after you made the last change. Only the new series interface is giving issues. You can see if gets resolved else leave it.

Moreover the session is logging out after a long time when the interface is idle.

So I feel we can close the issue. Please advise.

**Comment by amit-ros** [comment]
Hi Rohit,

I am in agreement that we can close this issue.

Thanks
Amit
