### ISSUE TITLE
Bug: Package Master: Unable to upload image

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#15]
The System is not uploading the image, which we are selecting in Package Master. 

The image is attached for reference,
![up](https://cloud.githubusercontent.com/assets/24309056/21466450/7e118884-c9f2-11e6-94a2-9804a93347f4.jpg)

**Comment by farhorizonindia** [comment]
Amit, the application is working but this issue looks like a permission issue to me.

**Comment by amit-ros** [comment]
This issue is happening because application is not able to login to the FTP server
FTP Server Address: ftp://ftp.adventureresortscruises.in/
User Id: "UploadImage"
Pwd: "Augurs@123"

Once that is fixed this issue should go away.

**Comment by farhorizonindia** [comment]
Amit, can you correct the userid and password to advenhgy and Rogerthat!1377$. Or let me know where I need to change this.

**Comment by amit-ros** [comment]
Code modified.
Please re-test.

**Comment by farhorizonindia** [comment]
Amit, its not working still. I tried upload the attached file for Pack5. And its not happening.
![p1380790](https://cloud.githubusercontent.com/assets/24309056/21517561/2016fb4e-cd06-11e6-833a-6cb294bd4249.JPG)

**Comment by amit-ros** [comment]
This issue is fixed. Revamped the code to upload the image.
This is deployed in production. Kindly retest.

**Comment by farhorizonindia** [comment]
The old code was working earlier, was there some issue in it for us to revamp the whole thing. 

Also we have uploaded the image and shows on the package master but the online link doesn't show the image for I'd pack5. 

Link for seeing the packages online is http://adventureresortscruises.in/Cruise/booking/PackageSearchResults.aspx?CId=1&date=0&RId=-River-

**Comment by amit-ros** [comment]
This issue is fixed but we got to talk about the fix.

**Comment by farhorizonindia** [comment]
We have checked and now its working fine.
