### ISSUE TITLE
3166 Bug: Reservations: Unable to update tourist details

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#16]
While we are adding the tourist details through the Add Tourist button on ViewBookings.aspx page, in booking no. 20161210003476 using URL http://admin.adventureresortscruises.in/ClientUI/touristdetails.aspx?bid=3476, After entring the data we click on save button. Its showing that the tourist has been added successfully, but its not updating the data.

This is running properly on our local application (www.farhorizonindia.net:8080/Reservations)

We have attached the screenshot of the message which we are getting after click save button.

![tourist details](https://cloud.githubusercontent.com/assets/24309056/21498836/53076ddc-cc56-11e6-9e9e-3ca0db311d5c.GIF)

**Comment by amit-ros** [comment]
This issue is found and fixed. Should be available to test in next roll-out.

**Comment by farhorizonindia** [comment]
Thank you Amit.
