### ISSUE TITLE
Bug: Permission issue on folder /httpdocs/Cruise/Booking/inv

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#17]
Amit, I have given the permission on the folder but I have a feeling that the application is not creating any pdf. Can you verify this on the local machine if the pdf file is getting created.
[Production Payment Error.docx](https://github.com/farhorizonindia/FH.RR/files/682161/Production.Payment.Error.docx)

**Comment by amit-ros** [comment]
Hey Rohit,

I believe this issue got resolved based on Mitsu's email. Please confirm.
