### ISSUE TITLE
3197 Bug: C Form: Unable to upload the C form

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#18]
While we are trying to upload the C Form through attached file we are getting an error "abcValue cannot be null. Parameter name: dataSet" on http://admin.adventureresortscruises.in/uploader.aspx?bid=3133&upload=Tourist page.

I have attached the both files (approved format and the file in which we are getting error) along with the screenshot of the error for reference. These files are in .xlsx format because GitHub does not allow to upload .csv files. Please convert these file in .csv before further testing.

![error](https://cloud.githubusercontent.com/assets/24309056/21635193/436a6924-d282-11e6-89b2-a7ff9de9cf7e.GIF)

[FH_TOURISTDETAILS.xlsx](https://github.com/farhorizonindia/FH.RR/files/684150/FH_TOURISTDETAILS.xlsx)

[C Form with error.xlsx](https://github.com/farhorizonindia/FH.RR/files/684155/C.Form.with.error.xlsx)

**Comment by amit-ros** [comment]
Hi Rohit,

I changed the file extension from xlsx to .csv and I was able to upload the data successfully. Kindly do the same at your end and try it once more. We can have a working session or this issue..

**Comment by farhorizonindia** [comment]
Dear Sir,

We have found problem in C Form. It's working in good condition but some cells not pick in proper area. While we are update the 2-3 records with the help of attached format the system is picking up the blank columns.

We have mark this and send it to you with screen shot. Please consider as per below attachment.

![booking details](https://cloud.githubusercontent.com/assets/24309056/22107304/05dd1a8c-de73-11e6-89d7-a8d768a503ac.gif)
![c form](https://cloud.githubusercontent.com/assets/24309056/22107311/0e724d70-de73-11e6-8bea-9706b8230eb9.gif)
![tourist list](https://cloud.githubusercontent.com/assets/24309056/22107317/16f40bfa-de73-11e6-97c8-fe3259c70175.gif)
[Blank column.xlsx](https://github.com/farhorizonindia/FH.RR/files/716588/Blank.column.xlsx)
[Incomplete details.xlsx](https://github.com/farhorizonindia/FH.RR/files/716589/Incomplete.details.xlsx)

**Comment by farhorizonindia** [comment]
We are getting the attached error while we are trying to upload the C-Form details for the booking no. 20150130002433. We are getting this error for all bookings.
![error c form](https://cloud.githubusercontent.com/assets/24309056/22236267/922a2be6-e22a-11e6-99e5-3f1b22683120.GIF)

**Comment by farhorizonindia** [comment]
We are still not able to upload the C-Form. The system is giving us option to select the file but while we click on the upload button the nothing happened.
