### ISSUE TITLE
3076: Bug: New Reservations: Problem when making charter bookings

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#3]
When the book button is pressed, the confirmation message of the booking does not show. It lands on the same screen removing the room category and room numbers section. 

Also the booking is actually made.

There are also cases where the booking shows its waitlisted when there is no other booking on that date. If we uncheck the charter flag the booking status becomes normal and does not show waitlisted.

Screen shot post book button is pressed is attached. And the booking which is waitlisted is also attached.

**Comment by farhorizonindia** [comment]
As shown when making a new cruise booking, after the book button is pressed the screen does not goto the booking updated page but stays there. 

Screenshot of a booking post book button is pressed.
![charter](https://cloud.githubusercontent.com/assets/24309056/21295203/fbf2b998-c575-11e6-8ea6-7595ba4fa625.PNG)

**Comment by amit-ros** [comment]
There is an issue in the stored proc 'up_Ins_BookingRoom'.

Following query is suppose to return a single value 
set @packageId=  (select packageId from dbo.tblCruiseOpenDates where AccomId=@iAccomId)  

But of course it doesn't and causes a failure.

Need to understand the need of this query in the system.

**Comment by amit-ros** [comment]
sp_helptext 'up_Ins_BookingRoom'

**Comment by amit-ros** [comment]
Stored proc is fixed. The query creating issues in stored proc is commented out as business does not want to change the flow of booking as of now.

**Comment by amit-ros** [comment]
Request business to validate the fix of this defect.

**Comment by farhorizonindia** [comment]
Thanks Amit. This is perfect.
