### ISSUE TITLE
3111: Bug: Reservations: Unable to change the status of the booking

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#5]
We are not able to changed the status of a booking from "booked" to "confirmed". We are getting the attached error while we are trying to changed the status.
![reservations error](https://cloud.githubusercontent.com/assets/24309056/21171660/797a7ab2-c1f3-11e6-8d36-3d81ec429073.GIF)
![reservations error 2](https://cloud.githubusercontent.com/assets/24309056/21171840/78eb502a-c1f4-11e6-9104-46868c66ee9c.GIF)

**Comment by farhorizonindia** [comment]
Will need to advise if this issue is reproducable

**Comment by farhorizonindia** [comment]
This issue happened again. This could be a database issue I feel. 

Check In:	15-Jan-2017 Check Out:	 22-Jan-2017 Nights:	 7 No. of Pax:	 2
Accomodation Type:	Cruise Accomodation Name:	 M V Mahabaahu
Booking Ref.:	D - Mr Makan x 02 Pax - Orange

Error: 
Server Error in '/' Application.

Object reference not set to an instance of an object.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 

Line 776:        tr.Cells.Add(tc);
Line 777:        tc = new TableCell();
Line 778:        tc.Text = obd[0].ArrivalCity.ToString();
Line 779:
Line 780:        tc.Width = 125;

Source File: d:\inetpub\vhosts\adventureresortscruises.in\admin.adventureresortcruises.in\ClientUI\afterBookingactions.aspx.cs    Line: 778 

Stack Trace: 

[NullReferenceException: Object reference not set to an instance of an object.]
   ClientUI_afterBookingactions.PrepareConfirmMail(BookingDTO[] obd, String st) in d:\inetpub\vhosts\adventureresortscruises.in\admin.adventureresortcruises.in\ClientUI\afterBookingactions.aspx.cs:778
   ClientUI_afterBookingactions.Bookconfirmformail(Int32 bookingId, String st) in d:\inetpub\vhosts\adventureresortscruises.in\admin.adventureresortcruises.in\ClientUI\afterBookingactions.aspx.cs:658
   ClientUI_afterBookingactions.Page_Load(Object sender, EventArgs e) in d:\inetpub\vhosts\adventureresortscruises.in\admin.adventureresortcruises.in\ClientUI\afterBookingactions.aspx.cs:62
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +51
   System.Web.UI.Control.OnLoad(EventArgs e) +92
   FarHorizon.Reservations.Bases.BasePages.BasePage.OnLoad(EventArgs e) in BasePage.cs:32
   FarHorizon.Reservations.Bases.BasePages.ClientBasePage.OnLoad(EventArgs e) in ClientBasePage.cs:26
   System.Web.UI.Control.LoadRecursive() +54
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +772

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34274

**Comment by farhorizonindia** [comment]
While we are trying to change the status of booking no. 20160311003027 we are getting the attached er
![confirmation error](https://cloud.githubusercontent.com/assets/24309056/21481009/055726ae-cb89-11e6-8d08-bcfe90cc3d74.JPG)
ror.

**Comment by amit-ros** [comment]
Fixed the issue and uploaded the latest code. Please re-test.

**Comment by farhorizonindia** [comment]
Thanks Amit, this is working.
