### ISSUE TITLE
3110: Repeat Bug: Unable to login

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#6]
We are again getting the login issue. The system is again not allowing us to login.
![login issue](https://cloud.githubusercontent.com/assets/24309056/21171725/bdd663f6-c1f3-11e6-9481-d5b051a7807d.GIF)
I have also attached the screenshot of the same for reference.

**Comment by amit-ros** [comment]
This issue is not reproducible as of now. Needs to keep our eyes open on this.

**Comment by farhorizonindia** [comment]
Its working now and is under observation.

**Comment by farhorizonindia** [comment]
This is working, but there is some other issue due to connection. Will close this and put that.
