### ISSUE TITLE
3123: Bug: Package Master: Incorrect numbers of night

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#7]
The drop down should show 2 and 5 but shows 3 and 5

**Comment by amit-ros** [comment]
I need the latest code for Rate folder. As we identified the code available to us is different from what is running on farhorizon public IP.

This issue can only be resolved once the latest code is available.

**Comment by farhorizonindia** [comment]
Amit, Madhvendra has deployed the application on the Mitsu Host in the Admin folder and I downloaded that on my local server and it is working fine. Madhvendra is saying this is the code which he has sent you on the 13 December 2016. Can you check again else we would need to do a screen share session again with them.

**Comment by farhorizonindia** [comment]
Drop down in the packages should be as follows:
Pack1 2 and 5 night
Pack2 3 and 4 night

Logic: Check the checkout based on the check in flag, and no of night =checkout-checkin (+1 if the checkout is for the last record)

And I have updated the checkout value of Pack2 to 1 which you had asked me to.

**Comment by amit-ros** [comment]
Logic to calculate the nights for the Child packages fixed to calculate correctly.

**Comment by farhorizonindia** [comment]
The issue is resolved.
