### ISSUE TITLE
3128 Change: Online Reservation: Remove Camps

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#8]
Remove the category Camps from the online booking page, screenshot attached.
![image](https://cloud.githubusercontent.com/assets/24309056/21295163/1d6d988c-c575-11e6-90ee-0305bce3cc59.png)

**Comment by amit-ros** [comment]
This issue is fixed. Should be available in next roll-out.

**Comment by amit-ros** [comment]
Fix is deployed. Needs to be tested on next roll-out.

**Comment by farhorizonindia** [comment]
Deployed.
